### ISSUE TITLE
Deploy workflow obsolete

### ISSUE THREAD

**Issue by celprov** [nipreps/sops-cookiecutter#3]
### What happened?

```
git clone --filter=blob:none --quiet https://github.com/Mandy91/mkdocs-toc-sidebar-plugin.git /tmp/pip-install-3yjf8t6m/mkdocs-toc-sidebar-plugin_3890bc91288c467baf1aefd047f1e8a7
  fatal: could not read Username for 'https://github.com/': No such device or address
```

The problem is that the repository https://github.com/Mandy91/mkdocs-toc-sidebar-plugin doesn't exist anymore. 

### What command did you use?

```shell
Merge PR
```

### What version of the software are you running?

-

### How are you running this software?

Other

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by oesteban** [comment]
Fixed with #10.
